---
apiVersion: v1
offerings:
  - name: deploy-arch-secrets-manager-private-cert-engine
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 571d2eb7-e416-40a4-aa95-be05e6155af8
    variations:
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
